//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_res { get; set; }
        public int id_r { get; set; }
        public int id_p { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Room Room { get; set; }
    }
}
