//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Diagnoses = new HashSet<Diagnose>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int id_p { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime birthdate { get; set; }
        public string father { get; set; }
        public string mother { get; set; }
        public bool sex { get; set; }
        public Nullable<decimal> phone { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> weight { get; set; }
        public bool smoker { get; set; }
        public Nullable<decimal> id_card { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<decimal> father_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnose> Diagnoses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
