//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAt
    {
        public int id_h { get; set; }
        public int id_d { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public Nullable<bool> sat { get; set; }
        public Nullable<bool> sun { get; set; }
        public Nullable<bool> mon { get; set; }
        public Nullable<bool> tue { get; set; }
        public Nullable<bool> wen { get; set; }
        public Nullable<bool> thu { get; set; }
        public Nullable<bool> fri { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
